version: '3.9'
services:
  configserver:
    build: ./ConfigServer
    image: configserverms:1.0
    container_name: configserver
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    depends_on:
      - eureka
  reservation:
    build: ./ReservationMS
    image: reservationms:1.0
    container_name: reservationms
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8888
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
  table:
    build: ./TableMS
    image: tablems:1.0
    container_name: tablems
    ports:
      - "8085:8085"
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8888
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
  stock:
    build: ./stock
    image: stockms:1.0
    container_name: stockms
    ports:
      - "8095:8095"
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8888
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
  menu:
    build: ./Menu_PlatMS
    image: menums:1.0
    container_name: menums
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8888
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
  commande:
    build: ./gestion-commandeMS
    image: commandems:1.0
    container_name: commandems
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8888
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
  facture:
    build: ./facture
    image: facturems:1.0
    container_name: facturems
    ports:
      - "8084:8084"
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8888
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
  employee:
    build: ./Employee
    image: employeems:1.0
    container_name: employeems
    ports:
      - "8088:8088"
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8888
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
  servicecommun:
    build: ./Service_comunn
    image: servicems:1.0
    container_name: job
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/marketingFidelite
    depends_on:
      - eureka
      - configserver
      - mongodb
  eureka:
    build: ./EurekaServer
    image: eurekams:1.0
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
  api-gateway:
    build: ./ApiGateway
    image: apigatewayms:1.0
    container_name: apigateway
    ports:
      - "8087:8087"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
    depends_on:
      - eureka
      - configserver
      - reservation
      - (votre MS)
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  

