
#spring.cloud.config.import-check.enabled=false
#spring.cloud.config.fail-fast=true
# Nom du service pour Eureka
spring.application.name=TableMS

# Port par défaut
server.port=8097

# H2 Database
spring.datasource.url=jdbc:h2:file:./Database/Data/Foodjoy
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Accès à /h2-console pour debug
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Spring RabbitMQ
spring.rabbitmq.host=localhost
# port par défaut du protocole AMQP
spring.rabbitmq.port=5672 
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Config Client (pour Spring Cloud Config, assume un config server)
spring.cloud.config.uri=http://localhost:8888

# Spring Data REST
#spring.data.rest.base-path=/api
# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always



spring.cloud.config.enabled=false