# Server Configuration
server.port=8080
<<<<<<< HEAD

# Application Name
spring.application.name=Facture

# H2 Database Configuration - Fichier persistant SIMPLIFIÉ
=======
# Application Name
spring.application.name=Facture
# H2 Database Configuration - Fichier persistant SIMPLIFI\uFFFD
>>>>>>> d2d904f (Ajout du dockerfile)
spring.datasource.url=jdbc:h2:file:./data/facturedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=
# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2
# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
<<<<<<< HEAD

# DÉSACTIVER l'initialisation SQL automatique
=======
# D\uFFFDSACTIVER l'initialisation SQL automatique
>>>>>>> d2d904f (Ajout du dockerfile)
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
# Logging
logging.level.com.esprit.ms.reservationms=DEBUG
logging.level.org.hibernate.SQL=DEBUG
<<<<<<< HEAD

spring.cloud.config.enabled=false
=======
spring.cloud.config.enabled=false
>>>>>>> d2d904f (Ajout du dockerfile)
