spring.application.name=Employee
# === Serveur ===
server.port=8088


# === DataSource H2 ===
spring.datasource.url=jdbc:h2:file:./Database/Data/Employee
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# === H2 Console ===
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# D�SACTIVER l'initialisation SQL automatique
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
# === Eureka Client ===
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Permet de d�marrer le service sans config server
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888
# Spring RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# === Reservation Service Base URL (direct MS or API Gateway) ===
# For direct ReservationMS access:
reservation.service.base-url=http://localhost:8089
# If you prefer routing via API Gateway (example port 8080), change to:
# reservation.service.base-url=http://localhost:8080
